KBB__USER_M_SERVICE__LOGO: str = 'Разработка логотипа'
KBB__USER_M_SERVICE__SITE_DEVELOPMENT: str = 'Разработка сайта'
KBB__USER_M_SERVICE__CHATBOT_DEVELOPMENT: str = 'Разработка чат-бота'
KBB__USER_M_SERVICE__DESIGN_VK_GROUPS: str = 'Оформление группы'
KBB__USER_M_SERVICE__MAIN_MENU: str = 'Главное меню'
